// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-orb/EditorialLeft.tsx": () => import("../components/mockups/hero-orb/EditorialLeft.tsx"),
  "./components/mockups/hero-orb/ForestSlate.tsx": () => import("../components/mockups/hero-orb/ForestSlate.tsx"),
  "./components/mockups/hero-orb/LuxuryBottom.tsx": () => import("../components/mockups/hero-orb/LuxuryBottom.tsx"),
  "./components/mockups/hero-orb/PureType.tsx": () => import("../components/mockups/hero-orb/PureType.tsx"),
  "./components/mockups/hero-orb/SplitColumn.tsx": () => import("../components/mockups/hero-orb/SplitColumn.tsx"),
  "./components/mockups/hero-orb/WarmAmber.tsx": () => import("../components/mockups/hero-orb/WarmAmber.tsx")
};
